NAME : SANDESH  NAKADE

CLASS : CSAI-D

ROLL NO: 34

PRN : 12412601

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Read CSV file
df_csv = pd.read_csv("/Exam_Score_Prediction.csv")


df_csv.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

# New section

In [ ]:
#shape of data
df_csv.shape

(20000, 13)

In [ ]:
#missing values
df_csv.isnull().sum()

student_id          0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [ ]:
#datatypes of each column
df_csv.dtypes

student_id            int64
age                   int64
gender               object
course               object
study_hours         float64
class_attendance    float64
internet_access      object
sleep_hours         float64
sleep_quality        object
study_method         object
facility_rating      object
exam_difficulty      object
exam_score          float64
dtype: object

In [ ]:
df_csv.rename(columns={"exam_score": "Marks"}, inplace=True)

In [ ]:
#finding zero values
(df_csv == 0).sum()

student_id          0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [ ]:
#selecting columns
#df_csv["study_hours"]

df_csv[["student_id", "class_attendance", "study_hours"]]

       student_id  class_attendance  study_hours
0               1              92.9         2.78
1               2              64.8         3.37
2               3              76.8         7.88
3               4              48.4         0.67
4               5              71.6         0.89
...           ...               ...          ...
19995       19997              71.3         6.50
19996       19998              41.6         3.71
19997       19999              68.2         7.88
19998       20000              76.3         4.60
19999       20001              47.9         7.50

[20000 rows x 3 columns]

In [ ]:
#sorting
df_csv.sort_values("class_attendance", ascending=False)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
12998,12999,18,female,b.sc,5.90,99.4,yes,8.6,poor,coaching,low,moderate,80.5
18575,18576,21,female,bba,6.73,99.4,yes,6.7,poor,mixed,medium,hard,72.3
2466,2467,19,other,b.tech,5.49,99.4,yes,4.5,good,online videos,high,moderate,75.6
11263,11264,18,female,diploma,0.19,99.4,yes,9.7,good,mixed,medium,moderate,58.1
11257,11258,17,other,b.tech,6.25,99.4,yes,5.2,average,self-study,medium,moderate,81.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11910,11911,18,male,b.com,2.87,40.6,yes,9.9,poor,self-study,medium,moderate,46.3
17749,17750,17,male,b.tech,3.78,40.6,yes,9.6,poor,online videos,medium,easy,38.4
17795,17796,19,other,b.tech,7.54,40.6,yes,4.3,good,group study,medium,moderate,47.0
5170,5171,21,male,b.com,2.82,40.6,yes,6.2,good,online videos,high,moderate,48.6
25,26,22,male,b.com,7.91,40.6,yes,4.3,good,group study,low,moderate,76.3

In [ ]:
#counting unique value
df_csv["gender"].value_counts()

gender
other     6726
male      6695
female    6579
Name: count, dtype: int64

In [ ]:
#converting datatypes
df_csv["age"] = df_csv["age"].astype(float)
df_csv["age"].dtype

dtype('float64')

In [ ]:
#grouped students mean exam score on the basis  of course
df_csv.groupby("course")["exam_score"].mean()

course
b.com      62.333197
b.sc       62.718993
b.tech     62.653529
ba         62.112214
bba        62.928127
bca        62.524078
diploma    62.330633
Name: exam_score, dtype: float64

In [ ]:
import pandas as pd

data = {
    "student_id": [1, 2, 3, 4],
    "age": [20, 21, 22, 20],
    "gender": ["Male", "Female", "Male", "Female"],
    "exam_score": [85, 72, 90, 60]
}

df = pd.DataFrame(data)

df

   student_id  age  gender  exam_score
0           1   20    Male          85
1           2   21  Female          72
2           3   22    Male          90
3           4   20  Female          60

In [ ]:
df.iloc[0:3]

   student_id  age  gender  exam_score
0           1   20    Male          85
1           2   21  Female          72
2           3   22    Male          90